### ISSUE TITLE
Channel Suggestion: Microsoft Teams

### ISSUE THREAD

**Issue by mikewheaton** [RecastAI/bot-connector#1]
Are there any plans to connect with [Microsoft Teams](https://dev.office.com/microsoft-teams)? It has support for bots and connectors.

**Comment by janteuni** [comment]
Hi @mikewheaton, I will add it in our roadmap! If you want contribute and implement it, it would be awesome! ;)

**Comment by patrickjoubert** [comment]
👍

**Comment by jhoudan** [comment]
Microsoft Teams is now available, through the Microsoft Bot Framework channel we've just added :rocket:
