### ISSUE TITLE
Microsoft Bot framework

### ISSUE THREAD

**Issue by cesarvarela** [RecastAI/bot-connector#11]
Hi, will this work with bots done using MS framework?

**Comment by cesarvarela** [comment]
To expand on this. 

Right now the MS bot connector is not open source, and it forces you to use their servers, with no plans at the moment from them to open source it, so an open source connector that works with their framework might be a good opportunity.

**Comment by jhoudan** [comment]
Hi,

We wanted the BotConnector to be as simple to use as possible, so all you need on the bot side is an endpoint on which the BotConnector will post the new messages it receives.
Do you know what will be required for it to be usable in the MS Bot Framework ?

**Comment by vijaypandiyan** [comment]
We are using Microsoft Bot Framework , do you have provision to connect with MS Bot and deploy it our own premises since MS Bot connector is not open source and need to register developer portal.

**Comment by cesarvarela** [comment]
@jhoudan I don't know, they are being kind of secretive about. I guess it's the hook to get people on their platform.

**Comment by vijaypandiyan** [comment]
@jhoudan looks like.  do you have any idea about any other open source Chatbot framework which can host own premises.

**Comment by cesarvarela** [comment]
@vijaypandiyan botkit

**Comment by jhoudan** [comment]
We've just added a connection to the Microsoft Bot Framework, giving us access to Skype, Microsoft Teams and much more. :-)
