### ISSUE TITLE
Can I use some webhook like in API.ai for specific intents? 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [RecastAI/bot-connector#21]

**Comment by thbeucher** [comment]
Hello,
It's currently not feasable but soon you will be able to do it in our next bot builder version (skills - release early october).

**Comment by jhoudan** [comment]
Hi,

We've released a new version of our bot builder, and it's now possible.
![Webhook url](https://user-images.githubusercontent.com/16180902/31935230-92fe532a-b8ae-11e7-8eba-8148c5b0430f.png)

You can either past a full url, or set a base url in your bot settings and set the last part of the path as the webhook url.
