### ISSUE TITLE
Channel suggestion: Telegram

### ISSUE THREAD

**Issue by uira** [RecastAI/bot-connector#3]
Did you have a deadline to get the Telegram integration working?

**Comment by jhoudan** [comment]
Hi uira,

We've created a github project, where you can have a look at the current roadmap: https://github.com/RecastAI/bot-connector/projects/1
There's no deadline yet for the integrations, but we will focus on the most asked by the community.

And if someone want to implement it, every PRs are welcome 👍

**Comment by jhoudan** [comment]
Telegram is now available :rocket:
