### ISSUE TITLE
publish the code to make it work with new webchat ?

### ISSUE THREAD

**Issue by fadomire** [RecastAI/bot-connector#31]
i see that you open sourced the webchat, there is a pollMessages in the webchat code that normally hit the bot-connector

could you publish the bot-connector code that should receive the request ?

**Comment by jhoudan** [comment]
We are currently reworking the way we maintain the Bot Connector repository and how we update it alongside the internal version we use (with an authentication layer on top of it).

As soon as we figured out how to do it efficiently, it will be updated with the code related to the webchat channel.
