### ISSUE TITLE
SAP Customer Engagement center is supported?

### ISSUE THREAD

**Issue by TechSkieur** [RecastAI/bot-connector#32]
Hey,

I notice that in Bot fallback channels, SAP Customer Engagement Center is one option. Does this mean Bot connector already supports Engagement Center? 

BRs,

yangyang

**Comment by lucasdchamps** [comment]
Hi @TechSkieur,

Indeed, this means Engagement Center is supported but only as a fallback channel, i.e using a fallback action, the conversation can be actively redirected to an agent in CEC.
