### ISSUE TITLE
Creation of new Channel does not work

### ISSUE THREAD

**Issue by shrivastavs** [RecastAI/bot-connector#36]
Hi,
I am trying to create a new channel using API https://api.recast.ai/connect/v1/channels
I am passing appropiate parameters but still it gives 500 server error.

**Comment by dbousque** [comment]
Hi @shrivastavs, this endpoint is not publicly documented, you shouldn't rely on it, we can make breaking changes to it at any moment. That being said, if you still want to do it, there probably is something missing in your request, like the `Content-Type` header, maybe your body is not well formatted, maybe a particular key you passed is invalid, maybe one is missing.

**Comment by shrivastavs** [comment]
Hi
Thanks for the suggestion.
I think I am using correct payload and content-type with developer token set in header. PLease find below sample payload and  URL:
URL: https://api.recast.ai/connect/v1/channels
Header parameters:
Content-Type: application/json
Authorization: Token 6a6e9184eae616f3fe367a1c19b41c50

Body:
{"isActivated":true, "slug":"testBot", "type":"telegram"}

BUt still it gives 500 server error.

**Comment by dbousque** [comment]
It's normal, you should send credentials as well.
