### ISSUE TITLE
Cannot POST /connectors

### ISSUE THREAD

**Issue by smartserveteam** [RecastAI/bot-connector#41]
Hi,

Brand new install, bot-connector responds fine on my ngrok-generated url.
However, when I try to run `curl -X POST 'http://localhost:8080/connectors' --data 'url=YOUR_BOT_ENDPOINT_URL'` (I replaced YOUR_BOT_ENDPOINT_URL with my ngrok url), it responds:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /connectors</pre>
</body>
</html>
```

I can see the routes and connectors look fine. Not sure why it's not working?

**Comment by hiro-v** [comment]
Hey there @smartserveteam, as I noticed, you should add v1 to the url, like below:
http://localhost:8080/connectors -> http://localhost:8080/v1/connectors
This is denoted in https://github.com/SAPConversationalAI/bot-connector/blob/master/src/routes/index.js 
Hope it helps :D

**Comment by smartserveteam** [comment]
Thanks!

**Comment by smartserveteam** [comment]
FYI, you might want to update the README
